apiVersion: v1
kind: Service
metadata:
  # creationTimestamp: "2021-08-10T03:19:35Z"
  name: shiny-loadbalancer
  # namespace: default
  # resourceVersion: "27641"
  # uid: f0f75150-f0dd-4249-9c68-4d6e60947aef
spec:
  type: LoadBalancer
  # clusterIP: 10.96.132.135
  # clusterIPs:
  # - 10.96.132.135
  # externalTrafficPolicy: Cluster
  # ipFamilies:
  # - IPv4
  # ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 31765
      port: 3838
      protocol: TCP
      targetPort: 3838
  selector:
    app: shiny-app
#   sessionAffinity: None
#   type: LoadBalancer
# status:
#   loadBalancer: {}
